### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [rhirst/tc359_project7#1]
This seems to work and it's one of the only projects I haven't been able to break so far! I do see [some indentation in `app.rb`](https://github.com/rhirst/tc359_project7/blob/master/app.rb) I'd like you to fix though. Can you use [this resource](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to do so?

Ping me when the repo is updated and I'll take another look.

**Comment by rhirst** [comment]
It should be all set now, thanks for the feedback!

**Comment by chrisvfritz** [comment]
:+1: Looking much better! This isn't something I need you to fix here, but for future reference, it's also good practice to delete debugging statements [like `puts params`](https://github.com/sjlawton/proj8/blob/master/views/index.erb) before committing.
